### ISSUE TITLE
Max Speed using IP over ICMP on Unlimited Bandiwidth Intenet

### ISSUE THREAD

**Issue by assegaf** [friedrich/hans#1]
Hi,

I wonder how much bandwidth we got max, for tunneling IP over ICMP, as we see tunneling IP over DNS is very very slow.

**Comment by abdulmueid** [comment]
I get around 7Mbps. Here are my parameters:

**Comment by friedrich** [comment]
@abdulmueid, your MTU seems a bit high. For optimal performance, it should match the mtu of the device you are using to connect to the internet. This is typically 1500. Check `ifconfig`. It looks like this:

   enp0s31f6: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
