### ISSUE TITLE
It's alive?

### ISSUE THREAD

**Issue by Samoylenko666** [friedrich/hans#22]
Now it's 2022, can I install this so that I get a tunnel between the server (linux) and my machine on windows or linux?

**Comment by friedrich** [comment]
Yes

**Comment by Samoylenko666** [comment]
thanks

**Comment by kovacs-andras** [comment]
> Now it's 2022, can I install this so that I get a tunnel between the server (linux) and my machine on windows or linux?

I'm using Fedora and Hans is available from the fedora repo. :sunglasses: 
Hans has withstood the test of time.
